### ISSUE TITLE
Add new  gallery section to home

### ISSUE THREAD

**Issue by STYersonH** [ACM-Chapter-Cusco/kratos#7]
### Motivation

In order to engagement more people to be part of the ACM or participate of the new event organized by the ACM, we will show pictures in the main page

---

### Description

To have this new gallery section in the home, assume that we have a list of images path like this:

```js
const carouselImages = ["image1.png", "image2.png", "image3.png", "image4.png", ...]

```

With this image list we need to create a carousel component to show images in the home page (see the desing and the reference).

- [ ] Add interactions and animations to have a nice slider, that mean we have an principal image in the carousel center
- [ ] Slider will pass automatically show all images in the list
- [ ] User can select any image from the list to show as principal in the carousel center
- [ ] Add left and right rows to navigate over the images list on the carousel

---

### Desing

![image](https://github.com/user-attachments/assets/3108cdb3-9ae9-4056-8f9c-500bd07b8444)

---

### References

- [Responsive Slider | Swiper Slider 3D-Coverflow Effect
](https://youtu.be/li-ylRo7VEc)

**Comment by Kleiber** [comment]
@STYersonH Can you review this issue?
